[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  framework = "vite"
  proxy = [
    { path = "/api/*", target = "http://localhost:8888" }
  ]
